### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by giga89** [staratlas-italia/saibase#56]
In order of priority

- [ ] Add quattrini buy page
- [ ] Add link to citizenship
- [ ] Add link to istutore (greyed out)
- [ ] Remove EV Tool
- [ ] Remove score tool
- [ ] Remove fleet simulator
- [ ] Instruct @giga89 to keep money from cittadino and istitutore bought 
- [ ] Removed not used part of repo
- [ ] Fix images ship deals
- [ ] Update ship explorer

**Comment by giga89** [comment]
@emberist
